name: football_intelligence
version: 1.0.0
config-version: 2
profile: football_intelligence
model-paths: ["warehouse/models"]
test-paths: ["warehouse/tests"]
macro-paths: ["warehouse/macros"]
clean-targets: ["target", "dbt_packages"]
models:
  football_intelligence:
    marts:
      +materialized: table

