"use client";

import {useState} from "react";
import {API,EmptyState,formatNumber,Player,PlayerSearch} from "../components";
import {ResearchPanel} from "../research-panel";
import {InlineLoader} from "../page-loader";

type SocialRow={platform:string;aggregate_date:string;topic:string;mention_count:number;sentiment_mean:string|null;data_as_of:string};
type SocialEnvelope={data:SocialRow[];meta:{source_status:string;data_as_of:string|null;sample_size:number;use:string}};
function tone(value:number){return value>.08?"mostly positive":value<-.08?"mostly negative":"broadly neutral"}

export default function MarketPage(){
  const [text,setText]=useState(""),[result,setResult]=useState<{score:number;label:string;matched_terms:string[]}|null>(null),[error,setError]=useState("");
  const [player,setPlayer]=useState<Player|null>(null),[social,setSocial]=useState<SocialEnvelope|null>(null),[socialError,setSocialError]=useState(""),[loading,setLoading]=useState(false);
  async function run(){try{const r=await fetch(`${API}/market/sentiment/score`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})}),p=await r.json();if(!r.ok)throw Error("Could not score this text");setResult(p.data)}catch(e){setError(e instanceof Error?e.message:"Unavailable")}}
  async function loadSocial(selected:Player){setPlayer(selected);setSocial(null);setSocialError("");setLoading(true);try{const response=await fetch(`${API}/players/${selected.player_id}/sentiment`);if(response.ok)setSocial(await response.json());else setSocialError("Fan conversation could not be loaded right now. The news above is unaffected.")}catch{setSocialError("Fan conversation could not be loaded right now. The news above is unaffected.")}setLoading(false)}
  const mentions=social?.data.reduce((sum,row)=>sum+row.mention_count,0)??0;
  const weighted=mentions?social!.data.reduce((sum,row)=>sum+Number(row.sentiment_mean??0)*row.mention_count,0)/mentions:0;
  return <main className="product-page" id="workspace-content"><div className="page-head"><div><div className="eyebrow">Press &amp; media</div><h1 className="page-title">What&apos;s being said</h1><p className="lede">Look up a player to see the latest news about them and how fans are talking about them online. Every item links to its source. None of it affects their football scores.</p></div></div>
    <section className="panel"><div className="card-top"><div><div className="eyebrow">Start here</div><h2>Choose a player</h2></div></div><PlayerSearch onSelect={loadSocial} label="Player"/>{!player&&<div className="media-preview"><div><strong>Latest news</strong><span>Recent headlines and reported claims, with the source and date for each.</span></div><div><strong>Fan conversation</strong><span>How often fans mention them on Bluesky, and whether the tone is positive or negative.</span></div></div>}</section>
    {player&&<ResearchPanel playerId={player.player_id} playerName={player.canonical_name}/>}
    {player&&<section className="panel"><div className="card-top"><div><div className="eyebrow">Fan conversation · Bluesky</div><h2>How fans are talking about {player.canonical_name}</h2></div><span className="tag">Context only</span></div><p className="analysis-copy">Public posts counted per day, with a simple positive or negative tone score. A mood check, not a verdict on the player.</p>{loading&&<InlineLoader label="Loading fan conversation…"/>}{socialError&&<div className="notice">{socialError}</div>}{!loading&&social&&!social.data.length&&<EmptyState title="No fan posts collected yet">We haven&apos;t collected any public posts about {player.canonical_name}. That means no data, not neutral opinion.</EmptyState>}{social&&social.data.length>0&&<div className="result-card"><div className="card-top"><div><h3>Tone is {tone(weighted)}</h3></div><div className="result-score">{formatNumber(weighted,2)}<small> on a −1 to +1 scale</small></div></div><p>{formatNumber(mentions,0)} posts over {social.data.length} days. Last updated {new Date(social.meta.data_as_of??social.data[0].data_as_of).toLocaleString()}.</p><div className="metric-list">{social.data.map(row=><div className="metric-row" key={`${row.aggregate_date}-${row.topic}`}><div><strong>{new Date(`${row.aggregate_date}T12:00:00`).toLocaleDateString(undefined,{dateStyle:"medium"})}</strong><small>{row.platform} · {row.topic}</small></div><b>{formatNumber(row.mention_count,0)} mentions · {tone(Number(row.sentiment_mean??0))}</b></div>)}</div><div className="insight"><strong>Read with care: </strong>this is a small sample of public posts. It can include jokes, sarcasm or coordinated posting, so never use it in place of scouting.</div></div>}</section>}
    {player&&<p className="research-note">Market value, transfers and contract for {player.canonical_name} are on their <a className="text-link" href={`/players/${player.player_id}`}>player profile →</a></p>}
    <section className="panel"><details className="role-builder"><summary className="card-top"><div><div className="eyebrow">Extra tool</div><h2>Check the tone of any text</h2><p className="analysis-copy">Paste an article, report or post you&apos;re allowed to use and see if it reads positive or negative.</p></div><span className="tag">Open +</span></summary><textarea value={text} maxLength={5000} onChange={e=>setText(e.target.value)} placeholder="Paste an article excerpt, scouting note or post…"/><button className="action" disabled={!text.trim()} onClick={run}>Check tone</button>{error&&<div className="notice">{error}</div>}{result&&<div className="result-card"><div className="result-score">{formatNumber(result.score,2)} <small>{result.label}</small></div><p>{result.matched_terms.length?`Words that drove the score: ${result.matched_terms.join(", ")}`:"No strongly positive or negative words found."}</p></div>}</details></section></main>}
